apiVersion: apps/v1
kind: Deployment
metadata:
  name: motd-deployment
  labels:
    app: motd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: motd
  template:
    metadata:
      labels:
        app: motd
    spec:
      containers:
      - name: motd
        image: magnorod/motd-api-image:f281a33b0080ccb4d805d61ae3eb74dbe7022674
        command: ["./motd-api.py"]
        args: ["80", "serveur web dans mon pod"]
        ports:
        - containerPort: 80
        env:
          - name: REDIS_URL
            value: "10.44.11.56"