apiVersion: apps/v1
kind: Deployment
metadata:
  name: motd-deployment
  labels:
    app: motd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: motd
  template:
    metadata:
      labels:
        app: motd
    spec:
      containers:
      - name: motd
        image: magnorod/motd-api-image:e128543079dc3d6f49a7490a358d1ba3d309b3a7
        command: ["./motd-api.py"]
        args: ["80", "serveur web dans mon pod"]
        ports:
        - containerPort: 80